-- MySQL Script generated by MySQL Workbench
-- Thu May 28 18:27:17 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema smartclass
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `assignment_files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `assignment_files` ;

CREATE TABLE IF NOT EXISTS `assignment_files` (
  `aFileId` INT NOT NULL AUTO_INCREMENT,
  `filePath` VARCHAR(100) NULL,
  `assignment` INT NOT NULL,
  `user` INT NOT NULL,
  PRIMARY KEY (`aFileId`, `assignment`, `user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assignments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `assignments` ;

CREATE TABLE IF NOT EXISTS `assignments` (
  `assignmentId` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NULL,
  `content` VARCHAR(10000) NULL,
  `availableFrom` TIMESTAMP NULL,
  `availableTo` TIMESTAMP NULL,
  `extensions` VARCHAR(100) NULL,
  `course` INT NOT NULL,
  PRIMARY KEY (`assignmentId`, `course`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `attends`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `attends` ;

CREATE TABLE IF NOT EXISTS `attends` (
  `user` INT NOT NULL,
  `course` INT NOT NULL,
  PRIMARY KEY (`user`, `course`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comments` ;

CREATE TABLE IF NOT EXISTS `comments` (
  `commentId` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(2000) NULL,
  `postDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `post` INT NOT NULL,
  `user` INT NOT NULL,
  PRIMARY KEY (`commentId`, `post`, `user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `courses` ;

CREATE TABLE IF NOT EXISTS `courses` (
  `courseId` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL,
  `token` VARCHAR(7) NULL,
  `status` TINYINT NULL,
  PRIMARY KEY (`courseId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grades` ;

CREATE TABLE IF NOT EXISTS `grades` (
  `gradeId` INT NOT NULL AUTO_INCREMENT,
  `grade` INT NULL,
  `comment` VARCHAR(500) NULL,
  `grading` INT NOT NULL,
  `user` INT NOT NULL,
  PRIMARY KEY (`gradeId`, `user`, `grading`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gradings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gradings` ;

CREATE TABLE IF NOT EXISTS `gradings` (
  `gradingId` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NULL,
  `minPoints` INT NULL,
  `maxPoints` INT NULL,
  `gradingDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `course` INT NOT NULL,
  `description` VARCHAR(1000) NULL,
  `publicScores` TINYINT NULL,
  PRIMARY KEY (`gradingId`, `course`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `material_files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `material_files` ;

CREATE TABLE IF NOT EXISTS `material_files` (
  `materialFileId` INT NOT NULL AUTO_INCREMENT,
  `filePath` VARCHAR(100) NULL,
  `title` VARCHAR(100) NULL,
  `material` INT NOT NULL,
  PRIMARY KEY (`materialFileId`, `material`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `material_shared`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `material_shared` ;

CREATE TABLE IF NOT EXISTS `material_shared` (
  `material` INT NOT NULL,
  `course` INT NOT NULL,
  `availableFrom` TIMESTAMP NULL,
  `availableTo` TIMESTAMP NULL,
  PRIMARY KEY (`material`, `course`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `materials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `materials` ;

CREATE TABLE IF NOT EXISTS `materials` (
  `materialId` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NULL,
  `content` VARCHAR(10000) NULL,
  `author` INT NOT NULL,
  `status` TINYINT NULL,
  PRIMARY KEY (`materialId`, `author`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `posts` ;

CREATE TABLE IF NOT EXISTS `posts` (
  `postId` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(2000) NULL,
  `postDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `course` INT NOT NULL,
  `user` INT NOT NULL,
  PRIMARY KEY (`postId`, `course`, `user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz_answers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quiz_answers` ;

CREATE TABLE IF NOT EXISTS `quiz_answers` (
  `quizFillId` INT NOT NULL,
  `qid` INT NOT NULL,
  `answer` LONGTEXT NULL,
  PRIMARY KEY (`qid`, `quizFillId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz_banks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quiz_banks` ;

CREATE TABLE IF NOT EXISTS `quiz_banks` (
  `bankId` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL,
  `author` INT NOT NULL,
  PRIMARY KEY (`bankId`, `author`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz_fills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quiz_fills` ;

CREATE TABLE IF NOT EXISTS `quiz_fills` (
  `quizFillId` INT NOT NULL AUTO_INCREMENT,
  `quiz` INT NOT NULL,
  `user` INT NOT NULL,
  `startTime` TIMESTAMP NULL,
  `finishTime` TIMESTAMP NULL,
  PRIMARY KEY (`quizFillId`, `quiz`, `user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz_questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quiz_questions` ;

CREATE TABLE IF NOT EXISTS `quiz_questions` (
  `questionId` INT NOT NULL AUTO_INCREMENT,
  `question` LONGTEXT NULL,
  `bank` INT NOT NULL,
  PRIMARY KEY (`questionId`, `bank`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quizes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quizes` ;

CREATE TABLE IF NOT EXISTS `quizes` (
  `quizId` INT NOT NULL AUTO_INCREMENT,
  `bank` INT NOT NULL,
  `course` INT NOT NULL,
  `questionCount` INT NULL,
  `randomizeQuestions` TINYINT NULL,
  `randomizeAnswers` TINYINT NULL,
  `availableFrom` TIMESTAMP NULL,
  `availableTo` TIMESTAMP NULL,
  `title` VARCHAR(200) NULL,
  `description` VARCHAR(10000) NULL,
  `length` INT NULL,
  PRIMARY KEY (`quizId`, `bank`, `course`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roles` ;

CREATE TABLE IF NOT EXISTS `roles` (
  `roleId` INT NOT NULL,
  `title` VARCHAR(40) NULL,
  PRIMARY KEY (`roleId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teaches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teaches` ;

CREATE TABLE IF NOT EXISTS `teaches` (
  `user` INT NOT NULL,
  `course` INT NOT NULL,
  PRIMARY KEY (`user`, `course`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_role` ;

CREATE TABLE IF NOT EXISTS `user_role` (
  `user` INT NOT NULL,
  `role` INT NOT NULL,
  PRIMARY KEY (`user`, `role`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NULL,
  `password` VARCHAR(128) NULL,
  `email` VARCHAR(100) NULL,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `votes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `votes` ;

CREATE TABLE IF NOT EXISTS `votes` (
  `user` INT NOT NULL,
  `option` INT NOT NULL,
  PRIMARY KEY (`user`, `option`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `voting_options`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `voting_options` ;

CREATE TABLE IF NOT EXISTS `voting_options` (
  `votingOptionId` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL,
  `voting` INT NOT NULL,
  PRIMARY KEY (`votingOptionId`, `voting`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `votings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `votings` ;

CREATE TABLE IF NOT EXISTS `votings` (
  `votingId` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NULL,
  `description` VARCHAR(2000) NULL,
  `availableFrom` TIMESTAMP NULL,
  `availableTo` TIMESTAMP NULL,
  `multiple` TINYINT NULL,
  `anonymous` TINYINT NULL,
  `result` TINYINT NULL,
  `course` INT NOT NULL,
  PRIMARY KEY (`votingId`, `course`))
ENGINE = InnoDB;